// for (let i = 0; i < 5; i++) {
//     console.log(i);
// }

// for (i=5; i>0; i--){
//     console.log(i)
// }
// let sum=0;
// for (let i=1; i<=10; i++){
//     sum+=i;
// }
// console.log(sum);
// ques-3
// for (let i=-10; i<=10; i++){
//     console.log(i);


// ques-4
// let num=7
// for (let i=1; i<=10; i++){
//     console.log(i*7)
// }

ques=5
let n=5
for (let i=1; i<=10; i++){
    console.log(n*i);
}
    
    